openapi: 3.0.0
info:
  title: "Bulk API"
  version: 2.0.0
  description: "The API for performing bulk uploads\n<h2>File Preparation</h2>\nThis API requires a file to be submitted with the appropriate schema. The details of that file's schema can be found at <a href='../../../../etl/docs/csv/import-schema.json'>File schema</a>\n"
  
tags:
  - name: "UploadAllParticipants"
servers:
  - url: /bulk/{stateAbbr}/v2
    variables:
      stateAbbr:
        default: none
        description: Lowercase two-letter postal code abbreviation
paths:
  '/upload_all_participants/{filename}':
    $ref: './../../etl/docs/openapi/uploadAllParticipants.yaml'
  '/upload/{filename}':
    $ref: './../../etl/docs/openapi/upload.yaml'
  '/uploads/{uploadIdentifier}':
    $ref: './../../etl/docs/openapi/getUploadById.yaml'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
    
