openapi: 3.0.0
info:
  title: "Duplicate Participation API"
  version: 2.0.0
  description: "The API where matching will occur"
servers:
  - url: "/match/v2"
paths:
  /find_matches:
    post:
      operationId: "Find matches"
      tags:
        - "Match"
      summary: "Search for all matching participant records using de-identified data"
      description: "Searches all state databases for any participant records that are an exact match to the `lds_hash` of persons provided in the request."
      parameters:
        - $ref: '../../match/docs/openapi/schemas/match-query.yaml#/components/parameters/From'
      requestBody:
        $ref: '../../match/docs/openapi/schemas/match-query.yaml#/MatchRequest'
      responses:
        '200':
          $ref: '../../match/docs/openapi/schemas/match-query.yaml#/components/responses/200'
        '400':
          $ref: '../../match/docs/openapi/schemas/match-query.yaml#/components/responses/400'
  /matches/{match_id}:
    get:
      operationId: "Get match record"
      tags:
        - "Match"
      summary: "Get a specific match record based on Match ID"
      description: "Retrieves a specific match record based on Match ID, if exists"
      responses:
        '200':
          $ref: '../../match/docs/openapi/schemas/match-record.yaml#/components/responses/200'
        '404':
          $ref: '../../match/docs/openapi/schemas/match-record.yaml#/components/responses/404'

security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
