version: 2
updates:
- package-ecosystem: nuget
  directory: "/dashboard/src/Piipan.Dashboard"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    # We’ve been staying with the 3.1.x versions of the .NET libraries in accordance with our decision to stay with .NET Core 3.1:
    # https://github.com/18F/piipan/blob/dev/docs/adr/0019-continue-to-use-net-core-3-1.md
    # We’ve been holding off on updating the Microsoft.NET.Sdk.Functions library to 4.x until MS updates their guidance on which version to use:
    # https://github.com/18F/piipan/pull/1951#issuecomment-947665260
    # These configs should be replicated on every nuget project
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/dashboard/src/Piipan.Dashboard"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/dashboard/tests/Piipan.Dashboard.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/etl/tests/Piipan.Etl.Func.BulkUpload.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/etl/tests/Piipan.Etl.Func.BulkUpload.IntegrationTests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match.Shared"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match.Orchestrator"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match/Piipan.Match.Core"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match/Piipan.Match.Api"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match/Piipan.Match.Func.Api"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.Orchestrator.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.Orchestrator.IntegrationTests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.Core.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.Func.Api.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Api"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Collect"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Api"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Core"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/metrics/tests/Piipan.Metrics.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/shared/src/Piipan.Shared"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/shared/tests/Piipan.Shared.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/query-tool/src/Piipan.QueryTool"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: npm
  directory: "/query-tool/src/Piipan.QueryTool"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/query-tool/tests/Piipan.QueryTool.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/participants/src/Piipan.Participants/Piipan.Participants.Api"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/participants/src/Piipan.Participants/Piipan.Participants.Core"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/participants/tests/Piipan.Participants.Core.IntegrationTests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
- package-ecosystem: nuget
  directory: "/participants/tests/Piipan.Participants.Core.Tests"
  schedule:
    interval: daily
    time: "09:00"
  ignore:
    - dependency-name: "Microsoft.AspNetCore.Authorization"
      versions: ["4.x", "5.x", "6.x", "7.x"]
    - dependency-name: "Microsoft.Azure.WebJobs.Extensions.EventGrid"
      versions: ["3.x"]
    - dependency-name: "Microsoft.Extensions.*"
      versions: ["4.x", "5.x", "6.x"]
    - dependency-name: "Microsoft.NET.Sdk.Functions"
      versions: ["4.x"]
