CREATE TABLE IF NOT EXISTS piipan.company
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    address1 character varying(50) COLLATE pg_catalog."default",
    address2 character varying(50) COLLATE pg_catalog."default",
    city character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT company_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS piipan.company
    OWNER to postgres;
