openapi: 3.0.0
info:
  title: Bulk API
  version: 2.0.0
  description: |
    The API for performing bulk uploads
    <h2>File Preparation</h2>
    This API requires a file to be submitted with the appropriate schema. The details of that file's schema can be found at <a href='../../../../etl/docs/csv/import-schema.json'>File schema</a>
tags:
  - name: UploadAllParticipants
servers:
  - url: '/bulk/{stateAbbr}/v2'
    variables:
      stateAbbr:
        default: none
        description: Lowercase two-letter postal code abbreviation
paths:
  '/upload_all_participants/{filename}':
    put:
      operationId: upload_all_participants
      summary: Upload a CSV file of bulk participant data
      tags:
        - Bulk Upload
      parameters:
        - name: filename
          in: path
          description: Name of file being uploaded
          required: true
          schema:
            type: string
        - in: header
          name: Content-Length
          schema:
            type: integer
          required: true
          description: Size in bytes of your file to be uploaded. A curl request will add this header by default when including a data or file parameter.
          example: 6413
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: File uploaded
          content:
            application/json:
              schema:
                title: Upload response
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                    description: The response payload. Will contain a data property with upload details.
                    required:
                      - upload_id
                    properties:
                      upload_id:
                        type: string
                        description: A unique upload_id for the successful upload.
              examples:
                Default:
                  description: An upload of a single CSV file of all the participants
                  value:
                    data:
                      upload_id: '0x8DA2EA86C4C2089'
        '401':
          description: Access denied
        '411':
          description: Content-Length not provided
  '/upload/{filename}':
    put:
      operationId: upload (deprecated)
      summary: Deprecated. This endpoint has been renamed to `upload_all_participants` and will be removed in a future version. Upload a CSV file of bulk participant data.
      tags:
        - Bulk Upload
      parameters:
        - name: filename
          in: path
          description: Name of file being uploaded
          required: true
          schema:
            type: string
        - in: header
          name: Content-Length
          schema:
            type: integer
          required: true
          description: Size in bytes of your file to be uploaded. A curl request will add this header by default when including a data or file parameter.
          example: 6413
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: File uploaded
          content:
            application/json:
              schema:
                title: Upload response
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                    description: The response payload. Will contain a data property with upload details.
                    required:
                      - upload_id
                    properties:
                      upload_id:
                        type: string
                        description: A unique upload_id for the successful upload.
              examples:
                Default:
                  description: An upload of a single CSV file of all the participants
                  value:
                    data:
                      upload_id: '0x8DA2EA86C4C2089'
        '401':
          description: Access denied
        '411':
          description: Content-Length not provided
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
