openapi: 3.0.0
info:
  title: Bulk API
  version: 2.0.0
  description: The API for performing bulk uploads
tags:
  - name: UploadAllParticipants
servers:
  - url: '/bulk/{stateAbbr}/v2'
    variables:
      stateAbbr:
        default: none
        description: Lowercase two-letter postal code abbreviation
paths:
  '/upload_all_participants/{filename}':
    put:
      responses:
        '201':
          description: File uploaded
          content:
            application/json:
              schema:
                title: Upload response
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                    description: The response payload. Will contain a data property with upload details.
                    required:
                      - upload_id
                    properties:
                      upload_id:
                        type: string
                        description: A unique upload_id for the successful upload.
              examples:
                Default:
                  description: An upload of a single CSV file of all the participants
                  value:
                    data:
                      upload_id: '0x8DA2EA86C4C2089'
  '/upload/{filename}':
    put:
      responses:
        '201':
          description: (Deprecated) File uploaded
          content:
            application/json:
              schema:
                title: Upload response
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                    description: The response payload. Will contain a data property with upload details.
                    required:
                      - upload_id
                    properties:
                      upload_id:
                        type: string
                        description: A unique upload_id for the successful upload.
              examples:
                Default:
                  description: An upload of a single CSV file of all the participants
                  value:
                    data:
                      upload_id: '0x8DA2EA86C4C2089'
      description: A Deprecated endpoint.
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
