openapi: 3.0.0
info:
  title: Match Collaboration API
  version: 1.0.0
  description: Internal API for resolving matching participant records
tags:
  - name: Collaboration
servers:
  - url: /v1
paths:
  '/matches/{match_id}':
    get:
      operationId: Get match record
      tags:
        - Collaboration
      summary: Get a specific match record based on Match ID
      description: 'Retrieves a specific match record based on Match ID, if exists'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                title: Match Record response - success
                type: object
                properties:
                  data:
                    type: object
                    description: 'The response payload representing a match record. Either an errors or data property will be present in the response, but not both.'
                    required:
                      - created_at
                      - match_id
                      - initiator
                      - states
                      - hash
                      - hash_type
                      - output
                      - invalid
                      - status
                    properties:
                      created_at:
                        type: string
                        format: date-time
                        example: '2021-04-12T23:20:50.52Z'
                        description: Match record's creation date/time
                      match_id:
                        type: string
                        description: Match record's human-readable unique identifier
                      initiator:
                        type: string
                        description: Match record's initiating state or territory
                      states:
                        type: array
                        description: List of states/territories involved in match
                        items:
                          type: string
                      hash:
                        type: string
                        description: Value of hash used to identify match. See docs/pprl.md for details
                      hash_type:
                        enum:
                          - ldshash
                        description: Type of hash used to identify match
                      input:
                        description: Original request data from real-time match request
                        type: object
                        required:
                          - lds_hash
                        properties:
                          lds_hash:
                            type: string
                            description: 'SHA-512 digest of participant''s last name, DoB, and SSN. See docs/pprl.md for details'
                            pattern: '^[0-9a-f]{128}$'
                      output:
                        description: Original response data from real-time match request
                        type: object
                        required:
                          - state
                          - participant_id
                          - case_id
                          - match_id
                        properties:
                          match_id:
                            type: string
                            description: Unique identifier for the match
                          state:
                            type: string
                            description: State/territory two-letter postal abbreviation
                          case_id:
                            type: string
                            description: Participant's state-specific case identifier. Can be the same for multiple participants.
                          participant_id:
                            type: string
                            description: Participant's state-specific identifier. Is unique to the participant. Must not be social security number or any PII.
                          benefits_end_month:
                            type: string
                            pattern: '^\d{4}-\d{2}$'
                            example: 2021-01
                            description: Participant's ending benefits month
                          recent_benefit_months:
                            type: array
                            items:
                              type: string
                              pattern: '^\d{4}-\d{2}$'
                              example: 2021-01
                            minItems: 0
                            maxItems: 3
                            description: 'List of up to the last 3 months that participant received benefits, in descending order. Each month is formatted as ISO 8601 year and month. Does not include current benefit month.'
                          protect_location:
                            type: boolean
                            nullable: true
                            example: true
                            description: Location protection flag for vulnerable individuals. True values indicate that the individual’s location must be protected from disclosure to avoid harm to the individual. Apply the same protections to true and null values.
                      invalid:
                        type: boolean
                        description: Indicator used for designating match as invalid
                      status:
                        enum:
                          - open
                          - closed
                        description: Match record's status
              examples:
                success:
                  description: A match record is returned
                  value:
                    data:
                      created_at: '2021-04-12T23:20:50.52Z'
                      match_id: ABC1234
                      initiator: eb
                      states:
                        - ea
                        - eb
                      hash: a3cab51dd68da2ac3e5508c8b0ee514ada03b9f166f7035b4ac26d9c56aa7bf9d6271e44c0064337a01b558ff63fd282de14eead7e8d5a613898b700589bcdec
                      hash_type: ldshash
                      input:
                        lds_hash: a3cab51dd68da2ac3e5508c8b0ee514ada03b9f166f7035b4ac26d9c56aa7bf9d6271e44c0064337a01b558ff63fd282de14eead7e8d5a613898b700589bcdec
                      output:
                        match_id: BCD2345
                        state: ea
                        case_id: string
                        participant_id: string
                        benefits_end_month: 2021-01
                        recent_benefit_months:
                          - 2021-05
                          - 2021-04
                          - 2021-03
                        protect_location: true
                      invalid: false
                      status: open
        '404':
          description: Match not found
          content:
            application/json:
              schema:
                title: Http Errors
                type: object
                properties:
                  errors:
                    type: array
                    description: 'Holds HTTP and other top-level errors. Either an errors or data property will be present in the top-level response, but not both.'
                    items:
                      type: object
                      required:
                        - status
                      properties:
                        status:
                          type: string
                          description: The HTTP status code
                        code:
                          type: string
                          description: The application-specific error code
                        title:
                          type: string
                          description: 'The short, human-readable summary of the error, consistent across all occurrences of the error'
                        detail:
                          type: string
                          description: The human-readable explanation specific to this occurrence of the error
              examples:
                not_found:
                  description: A match record is not found
                  value:
                    errors:
                      - status: '404'
                        code: XYZ
                        title: Not Found
                        detail: Match record not found
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
